### PR TITLE
adding testimonials section

### PR DESCRIPTION
**Pull request by alexanderschroyer**
added a few testimonials

### CODE REVIEW

**Comment by FolksyCarrot** [comment]
Change the first quote person.

**Comment by alexanderschroyer** [comment]
Endeavors is misspelled on line 48. Please fix.

**Comment by matt-rich-anderson** [comment]
looks good alex

**Review by FolksyCarrot — APPROVED** [review]
hjkgjkhghjlkghjkgjhkghjkg

**Pull request merged**
